name: Java CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B -DskipTests clean package

    - name: Test with Maven
      run: mvn test
      # Add steps for test result reporting here if needed

  deliver:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2

    - name: Deliver
      run: ./jenkins/scripts/deliver.sh
      # Ensure deliver.sh is executable and properly configured for GitHub Actions

